# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171112_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('choose', 'Choose'), ('tshirt', 'T-Shirt'), ('sweater', 'Sweater'), ('poster', 'Poster'), ('painting', 'Painting'), ('other', 'Other')], default='choose', max_length=6),
        ),
    ]
