# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171112_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Choose', 'Choose'), ('T-Shirt', 'T-Shirt'), ('Sweater', 'Sweater'), ('Poster', 'Poster'), ('Painting', 'Painting'), ('Other', 'Other')], default='choose', max_length=10),
        ),
    ]
