# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(blank=True, null=True, upload_to='product_files'),
        ),
    ]
